spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://127.0.0.1:3306/fido?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update